### ISSUE TITLE
Milestone 1 - Monday meeting

### ISSUE THREAD

**Issue by khbunyan** [UBC-MDS/dsci_525_group8#2]
Milestone 1 work:

- [x] Team Work Contract - @khbunyan 
- [x] Repo set up - @morganrosenberg50 
- [x] Downloading the data and Combining data CSVs - @nicovandenhooff 
- [x] Load the combined CSV to memory and perform a simple EDA - @jennifer-hoang 
- [x] Perform a simple EDA in R - @khbunyan 
- [x] Submission instructions - @morganrosenberg50 
- [x] Add runtimes
- [x] Comment on and compare runtimes

Submission schedule has been established, and is in a separate issue. 

Group agrees to meet again this thursday at 7pm.

**Comment by nicovandenhooff** [comment]
added a couple extra things above regarding runtimes just to ensure we don't miss them
